### ISSUE TITLE
yarn install command

### ISSUE THREAD

**Issue by Neelam-zanvar** [uniberg/kbn_sankey_vis#32]

**Comment by binarywang** [comment]
seems you need cd to plugins directory firstly

**Comment by Thiha-Aung1** [comment]
When i run the yarn install command i am getting the following error
yarn install v1.22.19
info No lockfile found.
$ node ../../preinstall_check
i got the same error , how can i run that yarn install and yarn compile command.?By the way i am using RHEL 7.
internal/modules/cjs/loader.js:638
throw err;
^

Error: Cannot find module '/etc/kibana/preinstall_check'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
at Function.Module._load (internal/modules/cjs/loader.js:562:25)
at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
at startup (internal/bootstrap/node.js:283:19)
at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
